### ISSUE TITLE
De-Grahaming

### ISSUE THREAD

**Issue by shortstuffsushi** [BranchMetrics/universal-link-validator#2]
Hi guys,

Glad to see development is still being approached for this project. I'm not sure why you've made it less restrictive, but perhaps you had your reasons for the sake of making it, if nothing else, easier for the user.

However, seeing as this is a fork of my repo, I'd appreciate if you update the items that are associated with me. I'm not entirely familiar with the process, but you have the license still under my name. Can you evaluate and implement the correct method for sublicensing your project?

Same with the package.json, though that's less important since it's not an npm published repository.

Lastly, and most noticeably from my end, you're using my New Relic key, which I really shouldn't have checked in to begin with. Please remove this.

Thanks, and good luck with this project.

**Comment by rubinsingh** [comment]
Hi Graham,

Thank you for all of your work! I have updated the appropriate assets in our repository and taken care of removing New Relic. 

Our reason for making the tool less restrictive was based on research that we performed with production Universal Link setups and how they validated in the original tool.

We appreciate all of the effort that was put into the original version.  If you would like to further the conversation, feel free to email me directly at rubin@branchmetrics.io.

Thanks,

Rubin

**Comment by shortstuffsushi** [comment]
Hi Rubin, thanks for the updates. I'm not sure that just replacing my name is right for licensing, but I'm also don't care that much.

If you guys want, I wouldn't mind pulling your changes back into my main repository -- it's got a fair number of followers, and is linked to by a number of sites. Could lead back to the Branch instance instead, since I'm just hosting on a crappy free Heroku instance.

Because you didn't fork through Github directly, there is no link to this project from there, so there's no real potential for discovery.

It's up to you guys, though. I'd be happy to add you as contributors if you want to go that direction.
